### ISSUE TITLE
Query for OnHeap:MissLatencyAverage returns wrong type

### ISSUE THREAD

**Issue by gibsong** [Terracotta-OSS/statistics#20]
This happens on all LatencyAverage queries.  Right now the return type is DurationHistory instead of AverageHistory. 

---------------------------------------------------------------------------------------------

method call that throws exception:
AverageHistory avgHistory = statisticsContext.getStatistic(AverageHistory.class, statName);

---------------------------------------------------------------------------------------------

Exception:
java.util.NoSuchElementException: OnHeap:MissLatencyAverage:org.terracotta.management.model.stats.history.AverageHistory
       at org.terracotta.management.model.stats.ContextualStatistics.getStatistic(ContextualStatistics.java:94)
       at org.ehcache.management.providers.statistics.StatsUtil.getExpectedValueFromAverageHistory(StatsUtil.java:236)
       at org.ehcache.management.providers.statistics.MissLatencyTest.test(MissLatencyTest.java:186)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
       at java.lang.reflect.Method.invoke(Method.java:597)
       at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
       at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
       at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
       at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
       at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
       at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
       at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
       at java.util.concurrent.FutureTask.run(FutureTask.java:138)
       at java.lang.Thread.run(Thread.java:662)

---------------------------------------------------------------------------------------------

Here is the ContextualStatistics output:
 
statisticsContext: ContextualStatistics{
capability='StatisticsCapability', 
context={cacheManagerName=myCacheManager, cacheName=myCache}, 
statistics={OnHeap:MissLatencyAverage={type='**DurationHistory**', value=[{timestamp=1479423304555, value=null},......, unit=NANOSECONDS}}}

**Comment by mathieucarbou** [comment]
there is a bug, I sent the fix to @gibsong for his PR and it will be fixed for both clustered and standalone in this pr: https://github.com/Terracotta-OSS/terracotta-platform/pull/186

**Comment by mathieucarbou** [comment]
(closing because not part of the stats project)
